# Generated by Django 2.1.2 on 2018-12-27 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relevamientocab',
            options={'verbose_name_plural': 'Relevamientos'},
        ),
        migrations.AlterModelOptions(
            name='relevamientodet',
            options={'verbose_name_plural': 'Relevamientos Cupo de Horas'},
        ),
        migrations.AlterModelOptions(
            name='relevamientoesp',
            options={'verbose_name_plural': 'Relevamientos Cupo de Horas Especiales'},
        ),
    ]
