# Generated by Django 2.1.2 on 2019-01-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0005_auto_20190109_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='relevamientocab',
            name='cantidadHrEsp',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Cantidad de Horas Especiales por Semana'),
        ),
    ]
