# Generated by Django 2.1.2 on 2019-01-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0006_relevamientocab_cantidadhresp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificacioncab',
            name='cantHoras',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Cantidad de Horas Normales'),
        ),
        migrations.AlterField(
            model_name='planificacioncab',
            name='cantHorasEsp',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Cantidad de Horas Especiales'),
        ),
        migrations.AlterField(
            model_name='planificacioncab',
            name='cantHorasNoc',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Cantidad de Horas Nocturnas'),
        ),
    ]
