# Generated by Django 2.1.2 on 2019-02-05 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Operarios', '0008_cargo_cargoasignado'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsigFiscalPuntoServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntoServicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='puntoServicio_AsigFiscalPuntoServicio', to='Operarios.PuntoServicio')),
                ('userFiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fiscal_AsigFiscalPuntoServicio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignacion Fiscal-PuntoServicio',
                'verbose_name_plural': 'Asignaciones Fiscales-PuntoServicio',
            },
        ),
        migrations.CreateModel(
            name='AsigJefeFiscal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userFiscal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Fiscal_AsigJefeFiscal', to=settings.AUTH_USER_MODEL)),
                ('userJefe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='JefeOp_AsigJefeFiscal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignacion Jefe-Fiscal',
                'verbose_name_plural': 'Asignaciones Jefe-Fiscales',
            },
        ),
        migrations.CreateModel(
            name='HisAsigFiscalPuntoServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha Final')),
                ('puntoServicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='puntoServicio_HisAsigFiscalPuntoServicio', to='Operarios.PuntoServicio')),
                ('userFiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fiscal_HisAsigFiscalPuntoServicio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historico Asignacion Fiscal-PuntoServicio',
                'verbose_name_plural': 'Historico Asignaciones Fiscales-PuntoServicio',
            },
        ),
        migrations.CreateModel(
            name='HisAsigJefeFiscal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha Final')),
                ('userFiscal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Fiscal_HisAsigJefeFiscal', to=settings.AUTH_USER_MODEL)),
                ('userJefe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='JefeOp_HisAsigJefeFiscal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historico Asignacion Jefe-Fiscal',
                'verbose_name_plural': 'Historico Asignaciones Jefe-Fiscales',
            },
        ),
    ]
