# Generated by Django 2.1.2 on 2019-02-20 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Operarios', '0009_asigfiscalpuntoservicio_asigjefefiscal_hisasigfiscalpuntoservicio_hisasigjefefiscal'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelevamientoCupoHoras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantHoras', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de Horas')),
                ('frecuencia', models.CharField(choices=[('SEM', 'Semanal'), ('DOM', 'Domingo'), ('FER', 'Feriado')], default='SEM', max_length=3, verbose_name='Frecuencia')),
            ],
            options={
                'verbose_name': 'Cupo de Horas',
                'verbose_name_plural': 'Cupos de Horas',
            },
        ),
        migrations.CreateModel(
            name='TipoHorario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoHorario', models.CharField(max_length=50, verbose_name='Tipo de Horario')),
                ('horaInicio', models.TimeField(blank=True, null=True, verbose_name='Horario Inicio')),
                ('horaFin', models.TimeField(blank=True, null=True, verbose_name='Horario Fin')),
            ],
            options={
                'verbose_name': 'Tipo de Horario',
                'verbose_name_plural': 'Tipos de Horarios',
            },
        ),
        migrations.CreateModel(
            name='TipoSalario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoSalario', models.CharField(max_length=50, verbose_name='Tipo de Salario')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion')),
                ('valor', models.IntegerField(blank=True, null=True, verbose_name='Valor de Salario')),
            ],
            options={
                'verbose_name': 'Tipo de Salario',
                'verbose_name_plural': 'Tipos de Salarios',
            },
        ),
        migrations.CreateModel(
            name='TipoServicioParticular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoServicioParticular', models.CharField(max_length=100, verbose_name='Tipo de Salario')),
            ],
            options={
                'verbose_name': 'Tipo de Servicio Particular',
                'verbose_name_plural': 'Tipos de Servicios Particulares',
            },
        ),
        migrations.AlterModelOptions(
            name='relevamientocab',
            options={'verbose_name_plural': 'Servicio Aprobado'},
        ),
        migrations.AlterModelOptions(
            name='relevamientodet',
            options={'verbose_name_plural': 'Servicios Particulares'},
        ),
        migrations.AlterModelOptions(
            name='relevamientoesp',
            options={'verbose_name_plural': 'Cupo de Horas Limpieza Profunda'},
        ),
        migrations.AddField(
            model_name='relevamientocab',
            name='fechaInicio',
            field=models.DateField(null=True, verbose_name='Fecha Inicio Cobertura'),
        ),
        migrations.AddField(
            model_name='relevamientocab',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relevamientocupohoras',
            name='relevamientoCab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Operarios.RelevamientoCab'),
        ),
        migrations.AddField(
            model_name='relevamientocupohoras',
            name='tipoHora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Operarios.TipoHorario'),
        ),
        migrations.AddField(
            model_name='relevamientocab',
            name='tipoSalario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Operarios.TipoSalario'),
        ),
        migrations.AddField(
            model_name='relevamientodet',
            name='tipoServPart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Operarios.TipoServicioParticular'),
        ),
    ]
