# Generated by Django 2.1.2 on 2019-02-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0011_auto_20190220_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relevamientocab',
            options={'verbose_name': 'Servicio Aprobado', 'verbose_name_plural': 'Servicios Aprobados'},
        ),
        migrations.AlterField(
            model_name='relevamientocupohoras',
            name='cantHoras',
            field=models.IntegerField(blank=True, db_column='cantHoras', null=True, verbose_name='Cantidad de Horas'),
        ),
    ]
