# Generated by Django 2.1.2 on 2019-02-23 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0013_auto_20190222_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelevamientoMensualeros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadM', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de Mensualeros')),
                ('sueldo', models.IntegerField(blank=True, null=True, verbose_name='Sueldo')),
                ('relevamientoCab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Operarios.RelevamientoCab')),
            ],
            options={
                'verbose_name': 'Mensualeros',
                'verbose_name_plural': 'Mensualeros',
            },
        ),
    ]
