# Generated by Django 2.1.2 on 2019-02-23 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0014_relevamientomensualeros'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relevamientomensualeros',
            old_name='cantidadM',
            new_name='mensuCantidad',
        ),
    ]
