# Generated by Django 2.1.2 on 2019-02-26 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0015_auto_20190223_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanificacionOpe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, null=True, verbose_name='Cantidad')),
                ('lun', models.BooleanField(default=False, verbose_name='Lunes')),
                ('mar', models.BooleanField(default=False, verbose_name='Martes')),
                ('mie', models.BooleanField(default=False, verbose_name='Miercoles')),
                ('jue', models.BooleanField(default=False, verbose_name='Jueves')),
                ('vie', models.BooleanField(default=False, verbose_name='Viernes')),
                ('sab', models.BooleanField(default=False, verbose_name='Sabado')),
                ('dom', models.BooleanField(default=False, verbose_name='Domingo')),
                ('fer', models.BooleanField(default=False, verbose_name='Feriado')),
                ('ent', models.TimeField(blank=True, null=True, verbose_name='Hora Inicio')),
                ('sal', models.TimeField(blank=True, null=True, verbose_name='Hora Fin')),
                ('corte', models.DecimalField(decimal_places=2, max_digits=2, null=True, verbose_name='corte')),
                ('total', models.IntegerField(blank=True, null=True, verbose_name='total')),
                ('especialista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Operarios.Especializacion')),
                ('planificacionCab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Operarios.PlanificacionCab')),
            ],
        ),
    ]
