# Generated by Django 2.1.2 on 2019-02-26 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0016_planificacionope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planificaciondet',
            name='especialista',
        ),
        migrations.RemoveField(
            model_name='planificaciondet',
            name='planificacionCab',
        ),
        migrations.DeleteModel(
            name='PlanificacionDet',
        ),
    ]
