# Generated by Django 2.1.2 on 2019-02-26 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0017_auto_20190226_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planificacionope',
            options={'verbose_name': 'Planificacion de Horas Operarios', 'verbose_name_plural': 'Planificaciones de Horas de Operarios'},
        ),
    ]
