# Generated by Django 2.1.2 on 2019-02-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0018_auto_20190226_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificacionope',
            name='corte',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='corte'),
        ),
    ]
