# Generated by Django 2.1.2 on 2019-03-05 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Operarios', '0019_auto_20190228_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionCab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaUltimaMod', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Relevamiento')),
                ('totalasignado', models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Total Asignado')),
                ('puntoServicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Operarios.PuntoServicio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignacion',
                'verbose_name_plural': 'Asignaciones',
            },
        ),
        migrations.CreateModel(
            name='AsignacionDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunEnt', models.TimeField(blank=True, null=True, verbose_name='Lunes entradas')),
                ('lunSal', models.TimeField(blank=True, null=True, verbose_name='Lunes salida')),
                ('marEnt', models.TimeField(blank=True, null=True, verbose_name='Martes entrada')),
                ('marSal', models.TimeField(blank=True, null=True, verbose_name='Martes salida')),
                ('mieEnt', models.TimeField(blank=True, null=True, verbose_name='Miercoles entrada')),
                ('mieSal', models.TimeField(blank=True, null=True, verbose_name='Miercoles salida')),
                ('jueEnt', models.TimeField(blank=True, null=True, verbose_name='Jueves entrada')),
                ('jueSal', models.TimeField(blank=True, null=True, verbose_name='Jueves salida')),
                ('vieEnt', models.TimeField(blank=True, null=True, verbose_name='Viernes entrada')),
                ('vieSal', models.TimeField(blank=True, null=True, verbose_name='Viernes salida')),
                ('sabEnt', models.TimeField(blank=True, null=True, verbose_name='Sabado entrada')),
                ('sabSal', models.TimeField(blank=True, null=True, verbose_name='Sabado salida')),
                ('domEnt', models.TimeField(blank=True, null=True, verbose_name='Domingo entrada')),
                ('domSal', models.TimeField(blank=True, null=True, verbose_name='Domingo salida')),
                ('asignacionCab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Operarios.AsignacionCab')),
                ('operario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Operarios.Operario')),
            ],
            options={
                'verbose_name': 'Asignacion Detalle',
                'verbose_name_plural': 'Asignacion Detalles',
            },
        ),
    ]
