# Generated by Django 2.1.2 on 2019-03-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0020_asignacioncab_asignaciondet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacioncab',
            name='totalasignado',
            field=models.CharField(max_length=8, null=True, verbose_name='Total Asignado'),
        ),
    ]
