# Generated by Django 2.1.2 on 2019-03-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0021_auto_20190308_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntoservicio',
            name='NumeroMarcador',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Numero Marcador'),
        ),
    ]
