# Generated by Django 2.1.2 on 2019-03-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0022_puntoservicio_numeromarcador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificacionope',
            name='corte',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='corte'),
        ),
    ]
