# Generated by Django 2.1.2 on 2019-03-21 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0023_auto_20190319_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorasNoProcesadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumCedulaOperario', models.CharField(max_length=30, verbose_name='N° Cedula')),
                ('Hentrada', models.TimeField(blank=True, null=True, verbose_name='Horario de entrada')),
                ('Hsalida', models.TimeField(blank=True, null=True, verbose_name='Horario de salida')),
                ('total', models.TimeField(blank=True, null=True, verbose_name='Total de Horas')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('TipoHora', models.CharField(max_length=10, verbose_name='Tipo de Hora')),
                ('puntoServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operarios.PuntoServicio')),
            ],
            options={
                'verbose_name': 'Hora No Procesada',
                'verbose_name_plural': 'Horas No Procesadas',
            },
        ),
        migrations.CreateModel(
            name='HorasProcesadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumCedulaOperario', models.CharField(max_length=30, verbose_name='N° Cedula')),
                ('Hentrada', models.TimeField(blank=True, null=True, verbose_name='Horario de entrada')),
                ('Hsalida', models.TimeField(blank=True, null=True, verbose_name='Horario de salida')),
                ('total', models.TimeField(blank=True, null=True, verbose_name='Total de Horas')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('TipoHora', models.CharField(max_length=10, verbose_name='Tipo de Hora')),
                ('comentario', models.CharField(blank=True, max_length=500, null=True, verbose_name='comentarios')),
                ('asignacionDet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Operarios.AsignacionDet')),
                ('puntoServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operarios.PuntoServicio')),
            ],
            options={
                'verbose_name': 'Hora Procesada',
                'verbose_name_plural': 'Horas Procesadass',
            },
        ),
    ]
