# Generated by Django 2.1.2 on 2019-03-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0024_horasnoprocesadas_horasprocesadas'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsmeEmMarcaciones',
            fields=[
                ('idpersonaevento', models.AutoField(db_column='IdPersonaEvento', primary_key=True, serialize=False)),
                ('codoperacion', models.CharField(blank=True, db_column='CodOperacion', max_length=2, null=True)),
                ('codpersona', models.CharField(blank=True, db_column='CodPersona', max_length=10, null=True)),
                ('codcategoria', models.CharField(blank=True, db_column='CodCategoria', max_length=2, null=True)),
                ('numlinea', models.CharField(blank=True, db_column='NumLinea', max_length=10, null=True)),
                ('codubicacion', models.CharField(blank=True, db_column='CodUbicacion', max_length=30, null=True)),
                ('fecha', models.DateTimeField(blank=True, db_column='Fecha', null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=20, null=True)),
            ],
            options={
                'db_table': 'ESME_EM_Marcaciones',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='horasnoprocesadas',
            name='comentario',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='comentarios'),
        ),
    ]
