# Generated by Django 2.1.2 on 2019-04-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0026_auto_20190402_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificacionope',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='total'),
        ),
    ]
