# Generated by Django 2.1.2 on 2019-04-09 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0030_auto_20190408_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asigjefefiscal',
            name='userFiscal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='FiscalAsigJefeFiscal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asigjefefiscal',
            name='userJefe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='JefeOpAsigJefeFiscal', to=settings.AUTH_USER_MODEL),
        ),
    ]
