# Generated by Django 2.1.2 on 2019-04-09 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0031_auto_20190409_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asigfiscalpuntoservicio',
            name='puntoServicio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='puntoServicioAsigFiscalPuntoServicio', to='Operarios.PuntoServicio'),
        ),
        migrations.AlterField(
            model_name='asigfiscalpuntoservicio',
            name='userFiscal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FiscalAsigFiscalPuntoServicio', to=settings.AUTH_USER_MODEL),
        ),
    ]
