# Generated by Django 2.1.2 on 2019-05-02 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0034_auto_20190411_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planificacionesp',
            name='cantHoras',
        ),
        migrations.RemoveField(
            model_name='planificacionope',
            name='corte',
        ),
        migrations.RemoveField(
            model_name='planificacionope',
            name='total',
        ),
        migrations.RemoveField(
            model_name='relevamientocupohoras',
            name='cantCHoras',
        ),
        migrations.RemoveField(
            model_name='relevamientoesp',
            name='cantHoras',
        ),
    ]
