# Generated by Django 2.1.2 on 2019-05-03 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0036_auto_20190502_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relevamientoesp',
            name='dia',
        ),
    ]
