# Generated by Django 2.1.2 on 2019-05-06 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0037_remove_relevamientoesp_dia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planificacionesp',
            name='dia',
        ),
    ]
