# Generated by Django 2.1.2 on 2019-05-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0038_remove_planificacionesp_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='planificacionesp',
            name='fechaLimpProf',
            field=models.DateField(null=True, verbose_name='Fecha Inicio Limpieza Prof'),
        ),
    ]
