# Generated by Django 2.1.2 on 2019-05-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0039_planificacionesp_fechalimpprof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relevamientocupohoras',
            name='cantCHoras',
            field=models.CharField(blank=True, db_column='cantHoras', max_length=8, null=True, verbose_name='Cantidad de Horas'),
        ),
    ]
