# Generated by Django 2.1.2 on 2019-05-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0040_auto_20190513_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificacionesp',
            name='cantHoras',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Cantidad de Horas'),
        ),
        migrations.AlterField(
            model_name='planificacionope',
            name='corte',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Corte'),
        ),
        migrations.AlterField(
            model_name='planificacionope',
            name='total',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='relevamientoesp',
            name='cantHoras',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Cantidad de Horas'),
        ),
    ]
