# Generated by Django 2.1.2 on 2019-05-16 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0041_auto_20190513_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionesProcesadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumCedulaOperario', models.CharField(max_length=30, verbose_name='N° Cedula')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('asignacionDet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Operarios.AsignacionDet')),
                ('puntoServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operarios.PuntoServicio')),
            ],
            options={
                'verbose_name': 'Asignacion Procesada',
                'verbose_name_plural': 'Asignaciones Procesadas',
            },
        ),
    ]
