# Generated by Django 2.1.2 on 2019-05-22 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0041_auto_20190513_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionDetAux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunEnt', models.TimeField(blank=True, null=True, verbose_name='Lunes entradas')),
                ('lunSal', models.TimeField(blank=True, null=True, verbose_name='Lunes salida')),
                ('marEnt', models.TimeField(blank=True, null=True, verbose_name='Martes entrada')),
                ('marSal', models.TimeField(blank=True, null=True, verbose_name='Martes salida')),
                ('mieEnt', models.TimeField(blank=True, null=True, verbose_name='Miercoles entrada')),
                ('mieSal', models.TimeField(blank=True, null=True, verbose_name='Miercoles salida')),
                ('jueEnt', models.TimeField(blank=True, null=True, verbose_name='Jueves entrada')),
                ('jueSal', models.TimeField(blank=True, null=True, verbose_name='Jueves salida')),
                ('vieEnt', models.TimeField(blank=True, null=True, verbose_name='Viernes entrada')),
                ('vieSal', models.TimeField(blank=True, null=True, verbose_name='Viernes salida')),
                ('sabEnt', models.TimeField(blank=True, null=True, verbose_name='Sabado entrada')),
                ('sabSal', models.TimeField(blank=True, null=True, verbose_name='Sabado salida')),
                ('domEnt', models.TimeField(blank=True, null=True, verbose_name='Domingo entrada')),
                ('domSal', models.TimeField(blank=True, null=True, verbose_name='Domingo salida')),
                ('fechaInicio', models.DateField(null=True, verbose_name='Fecha Inicio Operario')),
                ('asignacionCab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Operarios.AsignacionCab')),
                ('operario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Operarios.Operario')),
            ],
            options={
                'verbose_name': 'Asignacion Detalle Auxiliar',
                'verbose_name_plural': 'Asignacion Detalles Auxiliares',
            },
        ),
        migrations.AddField(
            model_name='asignaciondet',
            name='fechaInicio',
            field=models.DateField(null=True, verbose_name='Fecha Inicio Operario'),
        ),
    ]
