# Generated by Django 2.1.2 on 2019-05-25 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0042_auto_20190522_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operario',
            old_name='Banco',
            new_name='banco',
        ),
        migrations.RenameField(
            model_name='operario',
            old_name='Barrios',
            new_name='barrios',
        ),
        migrations.RenameField(
            model_name='operario',
            old_name='Ciudad',
            new_name='ciudad',
        ),
        migrations.RenameField(
            model_name='operario',
            old_name='Direccion',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='operario',
            old_name='Email',
            new_name='email',
        ),
        
        migrations.RenameField(
            model_name='operario',
            old_name='FechaNacimiento',
            new_name='fechaNacimiento',
        ),
        migrations.RenameField(
            model_name='operario',
            old_name='LugarNacimiento',
            new_name='lugarNacimiento',
        ),
        migrations.RenameField(
            model_name='operario',
            old_name='Nacionalidad',
            new_name='nacionalidad',
        ),
        migrations.RenameField(
            model_name='operario',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='operario',
            old_name='NombreContacto',
            new_name='nombreContacto',
        ),
        migrations.RenameField(
            model_name='operario',
            old_name='NroLegajo',
            new_name='nroLegajo',
        ),
        migrations.RenameField(
            model_name='operario',
            old_name='NumCedula',
            new_name='numCedula',
        ),
        migrations.RenameField(
            model_name='operario',
            old_name='NumPasaporte',
            new_name='numPasaporte',
        ),
        migrations.RenameField(
            model_name='operario',
            old_name='FechaFin',
            new_name='fechaFin',
        ),
         migrations.AddField(
            model_name='operario',
            name='ctaBanco',
            field=models.CharField(max_length=20, blank=True)
        )
    ]
