# Generated by Django 2.1.2 on 2019-05-25 22:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0043_auto_20190525_1618'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='operario',
            name='profesion',
            field=models.ManyToManyField(to='Operarios.Especializacion'),
        ),
        
    ]
