# Generated by Django 2.1.2 on 2019-05-27 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0045_auto_20190526_0021'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='relevamientocab',
            name='estado',
            field=models.CharField(default='Aprobado', max_length=30, verbose_name='Estado del relevamiento'),
        ),
        migrations.AddField(
            model_name='relevamientocab',
            name='fechaFin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Fin Cobertura'),
        ),
    ]
