# Generated by Django 2.1.2 on 2019-05-27 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0046_auto_20190527_0923'),
        ('Operarios', '0042_asignacionesprocesadas'),
    ]

    operations = [
    ]
