# Generated by Django 2.1.2 on 2019-05-27 20:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0047_merge_20190527_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operario',
            name='Clase',
        ),
        migrations.RemoveField(
            model_name='operario',
            name='CtaBanco',
        ),
        migrations.RemoveField(
            model_name='operario',
            name='Especialidad',
        ),
        migrations.RemoveField(
            model_name='operario',
            name='FechaInicio',
        ),
        migrations.RemoveField(
            model_name='operario',
            name='Profesion',
        ),
        migrations.RemoveField(
            model_name='operario',
            name='Telefono',
        ),
        migrations.AddField(
            model_name='asignaciondet',
            name='totalHoras',
            field=models.CharField(max_length=8, null=True, verbose_name='Total Asignado'),
        ),
        migrations.AddField(
            model_name='operario',
            name='apellido',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='operario',
            name='escolaridad',
            field=models.CharField(blank=True, max_length=70, verbose_name='Escolaridad'),
        ),
        migrations.AddField(
            model_name='operario',
            name='fechaInicio',
            field=models.DateField(null=True, verbose_name='Fecha Inicio'),
        ),
        migrations.AddField(
            model_name='operario',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operario',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operario',
            name='telefono',
            field=models.BigIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AddField(
            model_name='operario',
            name='telefonoContacto',
            field=models.BigIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Telefono Contacto'),
        ),
    ]
