# Generated by Django 2.1.2 on 2019-05-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0048_auto_20190527_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaciondetaux',
            name='totalHoras',
            field=models.CharField(max_length=8, null=True, verbose_name='Total Asignado Tabla Aux'),
        ),
    ]
