# Generated by Django 2.1.2 on 2019-05-30 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0051_auto_20190528_0913'),
        ('Operarios', '0043_feriados_parametros'),
    ]

    operations = [
    ]
