# Generated by Django 2.1.2 on 2019-05-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0053_asignaciondet_fechafin'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperariosDisponibles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_opeario', models.IntegerField()),
                ('nombres', models.CharField(max_length=200)),
                ('nroLegajo', models.CharField(max_length=6)),
                ('nombres_puntoServicio', models.CharField(max_length=200)),
                ('ids_puntoServicio', models.CharField(max_length=100)),
                ('totalHoras', models.FloatField()),
                ('perfil', models.CharField(max_length=400)),
                ('antiguedad', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
    ]
