# Generated by Django 2.1.2 on 2019-05-31 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0054_operariosdisponibles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operario',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='operario',
            name='longitud',
        ),
        migrations.RemoveField(
            model_name='operario',
            name='lugarNacimiento',
        ),
    ]
