# Generated by Django 2.1.2 on 2019-05-31 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0054_operariosdisponibles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operariosdisponibles',
            options={},
        ),
    ]
