# Generated by Django 2.1.2 on 2019-05-31 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0055_auto_20190530_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operariosdisponibles',
            options={'managed': False},
        ),
    ]
