# Generated by Django 2.1.2 on 2019-05-31 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0057_auto_20190530_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operario',
            name='latitud',
            field=models.CharField(blank=True, max_length=20, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='operario',
            name='longitud',
            field=models.CharField(blank=True, max_length=20, verbose_name='Longitud'),
        ),
    ]
