# Generated by Django 2.1.2 on 2019-05-31 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0058_auto_20190530_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperariosAsignacionDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_opeario', models.IntegerField()),
                ('nombres', models.CharField(max_length=200)),
                ('nroLegajo', models.CharField(max_length=6)),
                ('nombres_puntoServicio', models.CharField(max_length=200)),
                ('ids_puntoServicio', models.CharField(max_length=100)),
                ('totalHoras', models.FloatField()),
                ('perfil', models.CharField(max_length=400)),
                ('antiguedad', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Operario disponible',
                'verbose_name_plural': 'Operarios disponibles',
                'managed': True,
            },
        ),
    ]
