# Generated by Django 2.1.2 on 2019-05-31 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0059_operariosasignaciondet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operariosasignaciondet',
            options={'managed': False, 'verbose_name': 'Operario disponible', 'verbose_name_plural': 'Operarios disponibles'},
        ),
    ]
