# Generated by Django 2.1.2 on 2019-06-10 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0061_auto_20190601_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alertas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaHora', models.DateTimeField(verbose_name='Fecha hora del Alerta')),
                ('Estado', models.CharField(max_length=10, verbose_name='Estado')),
                ('Tipo', models.CharField(max_length=10, verbose_name='Tipo de Alerta')),
            ],
        ),
        migrations.AddField(
            model_name='alertas',
            name='Asignacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Operarios.AsignacionDet'),
        ),
        migrations.AddField(
            model_name='alertas',
            name='Operario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operarios.Operario'),
        ),
        migrations.AddField(
            model_name='alertas',
            name='PuntoServicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Operarios.PuntoServicio'),
        ),
    ]
