# Generated by Django 2.1.2 on 2019-06-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0062_auto_20190610_1516'),
    ]

    operations = [
        
    ]
