# Generated by Django 2.1.2 on 2019-06-15 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0063_auto_20190614_2300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OperariosAsignacionDet',
        ),
    ]
