# Generated by Django 2.1.2 on 2019-06-15 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0065_auto_20190614_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaciondet',
            name='supervisor',
            field=models.BooleanField(default=False, verbose_name='Supervisor'),
        ),
    ]
