# Generated by Django 2.1.2 on 2019-06-15 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0066_asignaciondet_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaciondet',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Operarios.Especializacion'),
        ),
    ]
