# Generated by Django 2.1.2 on 2019-06-15 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0067_asignaciondet_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaLibre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaInicio', models.CharField(max_length=10, verbose_name='Dia Inicio Libre')),
                ('horaInicio', models.TimeField(blank=True, null=True, verbose_name='Hora Inicio Libre')),
                ('diaFin', models.CharField(max_length=10, verbose_name='Dia Fin Libre')),
                ('horaFin', models.TimeField(blank=True, null=True, verbose_name='Hora Fin Libre')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Relevamiento')),
                ('asignacionDet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Operarios.AsignacionDet')),
            ],
        ),
    ]
