# Generated by Django 2.1.2 on 2019-06-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0069_operariosasignaciondet'),
    ]

    operations = [
        migrations.AddField(
            model_name='operariosasignaciondet',
            name='ids_perfil',
            field=models.CharField(db_column='ids_perfil', default='', max_length=100, verbose_name=' '),
        ),
    ]
