# Generated by Django 2.1.2 on 2019-06-21 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0071_alertaresp_horariosoperario'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertaresp',
            name='id_reemplazo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Operarios.Operario'),
        ),
    ]
