# Generated by Django 2.1.2 on 2019-06-21 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0064_remplazoscab_remplazosdet'),
        ('Operarios', '0072_alertaresp_id_reemplazo'),
    ]

    operations = [
    ]
