# Generated by Django 2.1.2 on 2019-06-21 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0073_merge_20190621_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertaresp',
            name='id_reemplazo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Operarios.RemplazosCab'),
        ),
    ]
