# Generated by Django 2.1.2 on 2019-06-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0074_auto_20190621_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertaresp',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Relevamiento'),
        ),
        migrations.AddField(
            model_name='horariosoperario',
            name='totalHoras',
            field=models.TimeField(blank=True, null=True, verbose_name='Cantidad horas'),
        ),
    ]
