# Generated by Django 2.1.2 on 2019-06-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0074_auto_20190621_1852'),
    ]

    operations = [
       
       
       
        migrations.AlterField(
            model_name='alertaresp',
            name='fechaRetorno',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Retorno'),
        ),
        migrations.AlterField(
            model_name='alertas',
            name='Estado',
            field=models.CharField(max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='horariosoperario',
            name='diaEntrada',
            field=models.CharField(db_column='diaEntrada', max_length=30, verbose_name='diaEntrada'),
        ),
        migrations.AlterField(
            model_name='horariosoperario',
            name='diaSalida',
            field=models.CharField(db_column='diaSalida', max_length=30, verbose_name='diaSalida'),
        ),
        migrations.AlterField(
            model_name='horariosoperario',
            name='horaEntrada',
            field=models.TimeField(blank=True, db_column='horaEntrada', verbose_name='horaEntrada'),
        ),
        migrations.AlterField(
            model_name='horariosoperario',
            name='horaSalida',
            field=models.TimeField(blank=True, db_column='horaSalida', verbose_name='horaSalida'),
        ),
    ]
