# Generated by Django 2.1.2 on 2019-06-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0075_auto_20190624_1126'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='remplazoscab',
            name='tipoRemplazo',
            field=models.CharField(max_length=15, verbose_name='Tipo de Remplazo'),
        ),
    ]
