# Generated by Django 2.1.2 on 2019-06-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0075_auto_20190622_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariosoperario',
            name='diaEntrada',
            field=models.CharField(db_column='diaEntrada', max_length=30, verbose_name='diaEntrada'),
        ),
        migrations.AlterField(
            model_name='horariosoperario',
            name='diaSalida',
            field=models.CharField(db_column='diaSalida', max_length=30, verbose_name='diaSalida'),
        ),
        migrations.AlterField(
            model_name='horariosoperario',
            name='horaEntrada',
            field=models.TimeField(blank=True, db_column='horaEntrada', verbose_name='horaEntrada'),
        ),
        migrations.AlterField(
            model_name='horariosoperario',
            name='horaSalida',
            field=models.TimeField(blank=True, db_column='horaSalida', verbose_name='horaSalida'),
        ),
        migrations.AlterField(
            model_name='horariosoperario',
            name='totalHoras',
            field=models.TimeField(blank=True, db_column='totalHoras', null=True, verbose_name='totalHoras'),
        ),
    ]
