# Generated by Django 2.1.2 on 2019-06-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0076_auto_20190622_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariosoperario',
            name='idOrden',
            field=models.IntegerField(db_column='idOrden', null=True, verbose_name=''),
        ),
    ]
