# Generated by Django 2.1.2 on 2019-06-25 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0076_auto_20190625_0929'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='remplazosdet',
            name='remplazoCab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Operarios.RemplazosCab'),
        ),
    ]
