# Generated by Django 2.1.2 on 2019-06-22 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0077_horariosoperario_idorden'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HorariosOperario',
        ),
    ]
