# Generated by Django 2.1.2 on 2019-06-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0077_auto_20190625_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
        
    ]
