# Generated by Django 2.1.2 on 2019-06-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0078_delete_horariosoperario'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorariosOperario',
            fields=[
                ('idOrden', models.IntegerField(db_column='idOrden', primary_key=True, serialize=False, verbose_name='idOrden')),
                ('diaEntrada', models.CharField(db_column='diaEntrada', max_length=30, verbose_name='diaEntrada')),
                ('horaEntrada', models.TimeField(blank=True, db_column='horaEntrada', verbose_name='horaEntrada')),
                ('diaSalida', models.CharField(db_column='diaSalida', max_length=30, verbose_name='diaSalida')),
                ('horaSalida', models.TimeField(blank=True, db_column='horaSalida', verbose_name='horaSalida')),
                ('totalHoras', models.TimeField(blank=True, db_column='totalHoras', null=True, verbose_name='totalHoras')),
            ],
            options={
                'verbose_name': 'Horarios Operario',
                'verbose_name_plural': 'Horarios Operario',
            },
        ),
    ]
