# Generated by Django 2.1.2 on 2019-06-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0079_auto_20190627_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialibre',
            name='asignacionDet',
        ),
        migrations.RemoveField(
            model_name='dialibre',
            name='diaFin',
        ),
        migrations.RemoveField(
            model_name='dialibre',
            name='diaInicio',
        ),
        migrations.RemoveField(
            model_name='dialibre',
            name='horaFin',
        ),
        migrations.RemoveField(
            model_name='dialibre',
            name='horaInicio',
        ),
        
    ]
