# Generated by Django 2.1.2 on 2019-06-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0079_horariosoperario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertaresp',
            name='fechaRetorno',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Retorno'),
        ),
    ]
