# Generated by Django 2.1.2 on 2019-06-28 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0080_auto_20190628_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialibre',
            name='domEnt',
            field=models.TimeField(blank=True, null=True, verbose_name='Domingo entrada'),
        ),
        migrations.AddField(
            model_name='dialibre',
            name='domSal',
            field=models.TimeField(blank=True, null=True, verbose_name='Domingo salida'),
        ),
        migrations.AddField(
            model_name='dialibre',
            name='id_operario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Operarios.Operario'),
        ),
        migrations.AddField(
            model_name='dialibre',
            name='jueEnt',
            field=models.TimeField(blank=True, null=True, verbose_name='Jueves entrada'),
        ),
        migrations.AddField(
            model_name='dialibre',
            name='jueSal',
            field=models.TimeField(blank=True, null=True, verbose_name='Jueves salida'),
        ),
        migrations.AddField(
            model_name='dialibre',
            name='lunEnt',
            field=models.TimeField(blank=True, null=True, verbose_name='Lunes entradas'),
        ),
        migrations.AddField(
            model_name='dialibre',
            name='lunSal',
            field=models.TimeField(blank=True, null=True, verbose_name='Lunes salida'),
        ),
        migrations.AddField(
            model_name='dialibre',
            name='marEnt',
            field=models.TimeField(blank=True, null=True, verbose_name='Martes entrada'),
        ),
        migrations.AddField(
            model_name='dialibre',
            name='marSal',
            field=models.TimeField(blank=True, null=True, verbose_name='Martes salida'),
        ),
        migrations.AddField(
            model_name='dialibre',
            name='mieEnt',
            field=models.TimeField(blank=True, null=True, verbose_name='Miercoles entrada'),
        ),
        migrations.AddField(
            model_name='dialibre',
            name='mieSal',
            field=models.TimeField(blank=True, null=True, verbose_name='Miercoles salida'),
        ),
        migrations.AddField(
            model_name='dialibre',
            name='sabEnt',
            field=models.TimeField(blank=True, null=True, verbose_name='Sabado entrada'),
        ),
        migrations.AddField(
            model_name='dialibre',
            name='sabSal',
            field=models.TimeField(blank=True, null=True, verbose_name='Sabado salida'),
        ),
        migrations.AddField(
            model_name='dialibre',
            name='vieEnt',
            field=models.TimeField(blank=True, null=True, verbose_name='Viernes entrada'),
        ),
        migrations.AddField(
            model_name='dialibre',
            name='vieSal',
            field=models.TimeField(blank=True, null=True, verbose_name='Viernes salida'),
        ),
        
    ]
