# Generated by Django 2.1.2 on 2019-07-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0081_auto_20190628_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='asigfiscalpuntoservicio',
            name='vfechaFin',
            field=models.DateTimeField(null=True, verbose_name='Fecha Fin Reg'),
        ),
        migrations.AddField(
            model_name='asigfiscalpuntoservicio',
            name='vfechaInicio',
            field=models.DateTimeField(null=True, verbose_name='Fecha Inicio Reg'),
        ),
        migrations.AddField(
            model_name='asigfiscalpuntoservicio',
            name='vregistro',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor de Salario'),
        ),
        migrations.AddField(
            model_name='asigjefefiscal',
            name='vfechaFin',
            field=models.DateTimeField(null=True, verbose_name='Fecha Fin Reg'),
        ),
        migrations.AddField(
            model_name='asigjefefiscal',
            name='vfechaInicio',
            field=models.DateTimeField(null=True, verbose_name='Fecha Inicio Reg'),
        ),
        migrations.AddField(
            model_name='asigjefefiscal',
            name='vregistro',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor de Salario'),
        ),
        migrations.AddField(
            model_name='asignacioncab',
            name='vfechaFin',
            field=models.DateTimeField(null=True, verbose_name='Fecha Fin Reg'),
        ),
        migrations.AddField(
            model_name='asignacioncab',
            name='vfechaInicio',
            field=models.DateTimeField(null=True, verbose_name='Fecha Inicio Reg'),
        ),
        migrations.AddField(
            model_name='asignacioncab',
            name='vregistro',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor de Salario'),
        ),
        migrations.AddField(
            model_name='asignaciondet',
            name='vfechaFin',
            field=models.DateTimeField(null=True, verbose_name='Fecha Fin Reg'),
        ),
        migrations.AddField(
            model_name='asignaciondet',
            name='vfechaInicio',
            field=models.DateTimeField(null=True, verbose_name='Fecha Inicio Reg'),
        ),
        migrations.AddField(
            model_name='asignaciondet',
            name='vregistro',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor de Salario'),
        ),
        migrations.AddField(
            model_name='planificacioncab',
            name='vfechaFin',
            field=models.DateTimeField(null=True, verbose_name='Fecha Fin Reg'),
        ),
        migrations.AddField(
            model_name='planificacioncab',
            name='vfechaInicio',
            field=models.DateTimeField(null=True, verbose_name='Fecha Inicio Reg'),
        ),
        migrations.AddField(
            model_name='planificacioncab',
            name='vregistro',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor de Salario'),
        ),
        migrations.AddField(
            model_name='planificacionesp',
            name='vfechaFin',
            field=models.DateTimeField(null=True, verbose_name='Fecha Fin Reg'),
        ),
        migrations.AddField(
            model_name='planificacionesp',
            name='vfechaInicio',
            field=models.DateTimeField(null=True, verbose_name='Fecha Inicio Reg'),
        ),
        migrations.AddField(
            model_name='planificacionesp',
            name='vregistro',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor de Salario'),
        ),
        migrations.AddField(
            model_name='planificacionope',
            name='vfechaFin',
            field=models.DateTimeField(null=True, verbose_name='Fecha Fin Reg'),
        ),
        migrations.AddField(
            model_name='planificacionope',
            name='vfechaInicio',
            field=models.DateTimeField(null=True, verbose_name='Fecha Inicio Reg'),
        ),
        migrations.AddField(
            model_name='planificacionope',
            name='vregistro',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor de Salario'),
        ),
        migrations.AddField(
            model_name='puntoservicio',
            name='vfechaFin',
            field=models.DateTimeField(null=True, verbose_name='Fecha Fin Reg'),
        ),
        migrations.AddField(
            model_name='puntoservicio',
            name='vfechaInicio',
            field=models.DateTimeField(null=True, verbose_name='Fecha Inicio Reg'),
        ),
        migrations.AddField(
            model_name='puntoservicio',
            name='vregistro',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor de Salario'),
        ),
        migrations.AddField(
            model_name='relevamientocab',
            name='vfechaFin',
            field=models.DateTimeField(null=True, verbose_name='Fecha Fin Reg'),
        ),
        migrations.AddField(
            model_name='relevamientocab',
            name='vfechaInicio',
            field=models.DateTimeField(null=True, verbose_name='Fecha Inicio Reg'),
        ),
        migrations.AddField(
            model_name='relevamientocab',
            name='vregistro',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor de Salario'),
        ),
        migrations.AddField(
            model_name='relevamientocupohoras',
            name='vfechaFin',
            field=models.DateTimeField(null=True, verbose_name='Fecha Fin Reg'),
        ),
        migrations.AddField(
            model_name='relevamientocupohoras',
            name='vfechaInicio',
            field=models.DateTimeField(null=True, verbose_name='Fecha Inicio Reg'),
        ),
        migrations.AddField(
            model_name='relevamientocupohoras',
            name='vregistro',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor de Salario'),
        ),
        migrations.AddField(
            model_name='relevamientodet',
            name='vfechaFin',
            field=models.DateTimeField(null=True, verbose_name='Fecha Fin Reg'),
        ),
        migrations.AddField(
            model_name='relevamientodet',
            name='vfechaInicio',
            field=models.DateTimeField(null=True, verbose_name='Fecha Inicio Reg'),
        ),
        migrations.AddField(
            model_name='relevamientodet',
            name='vregistro',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor de Salario'),
        ),
        migrations.AddField(
            model_name='relevamientoesp',
            name='vfechaFin',
            field=models.DateTimeField(null=True, verbose_name='Fecha Fin Reg'),
        ),
        migrations.AddField(
            model_name='relevamientoesp',
            name='vfechaInicio',
            field=models.DateTimeField(null=True, verbose_name='Fecha Inicio Reg'),
        ),
        migrations.AddField(
            model_name='relevamientoesp',
            name='vregistro',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor de Salario'),
        ),
        migrations.AddField(
            model_name='relevamientomensualeros',
            name='vfechaFin',
            field=models.DateTimeField(null=True, verbose_name='Fecha Fin Reg'),
        ),
        migrations.AddField(
            model_name='relevamientomensualeros',
            name='vfechaInicio',
            field=models.DateTimeField(null=True, verbose_name='Fecha Inicio Reg'),
        ),
        migrations.AddField(
            model_name='relevamientomensualeros',
            name='vregistro',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor de Salario'),
        ),
    ]
