# Generated by Django 2.1.2 on 2019-07-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0082_auto_20190703_1559'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='asignacioncab',
            name='reAsignar',
            field=models.BooleanField(default=False, verbose_name='Re asignar'),
        ),
        migrations.AddField(
            model_name='planificacioncab',
            name='rePlanificar',
            field=models.BooleanField(default=False, verbose_name='Re planificar'),
        ),
    ]
