# Generated by Django 2.1.2 on 2019-07-23 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0084_auto_20190723_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='CupoReal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anho', models.IntegerField(blank=True, null=True, verbose_name='Anho calendario')),
                ('mes', models.CharField(max_length=2, verbose_name='Mes del anho')),
                ('cupoCalculado', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de horas totales reales por mes')),
                ('puntoServicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Operarios.PuntoServicio')),
            ],
        ),
        
    ]
