# Generated by Django 2.1.2 on 2019-07-24 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Operarios', '0085_auto_20190723_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistAsigJefeFiscal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vfechaInicio', models.DateTimeField(null=True, verbose_name='Fecha Inicio Reg')),
                ('vfechaFin', models.DateTimeField(null=True, verbose_name='Fecha Fin Reg')),
                ('vregistro', models.IntegerField(blank=True, null=True, verbose_name='Valor de Salario')),
                ('userFiscal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='HistFiscalAsigJefeFiscal', to=settings.AUTH_USER_MODEL)),
                ('userJefe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HistJefeOpAsigJefeFiscal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='asigfiscalpuntoservicio',
            name='vfechaFin',
        ),
        migrations.RemoveField(
            model_name='asigfiscalpuntoservicio',
            name='vfechaInicio',
        ),
        migrations.RemoveField(
            model_name='asigfiscalpuntoservicio',
            name='vregistro',
        ),
        migrations.RemoveField(
            model_name='asigjefefiscal',
            name='vfechaFin',
        ),
        migrations.RemoveField(
            model_name='asigjefefiscal',
            name='vfechaInicio',
        ),
        migrations.RemoveField(
            model_name='asigjefefiscal',
            name='vregistro',
        ),
        migrations.RemoveField(
            model_name='asignacioncab',
            name='vfechaFin',
        ),
        migrations.RemoveField(
            model_name='asignacioncab',
            name='vfechaInicio',
        ),
        migrations.RemoveField(
            model_name='asignacioncab',
            name='vregistro',
        ),
        migrations.RemoveField(
            model_name='asignaciondet',
            name='vfechaFin',
        ),
        migrations.RemoveField(
            model_name='asignaciondet',
            name='vfechaInicio',
        ),
        migrations.RemoveField(
            model_name='asignaciondet',
            name='vregistro',
        ),
        migrations.RemoveField(
            model_name='planificacioncab',
            name='vfechaFin',
        ),
        migrations.RemoveField(
            model_name='planificacioncab',
            name='vfechaInicio',
        ),
        migrations.RemoveField(
            model_name='planificacioncab',
            name='vregistro',
        ),
        migrations.RemoveField(
            model_name='planificacionesp',
            name='vfechaFin',
        ),
        migrations.RemoveField(
            model_name='planificacionesp',
            name='vfechaInicio',
        ),
        migrations.RemoveField(
            model_name='planificacionesp',
            name='vregistro',
        ),
        migrations.RemoveField(
            model_name='planificacionope',
            name='vfechaFin',
        ),
        migrations.RemoveField(
            model_name='planificacionope',
            name='vfechaInicio',
        ),
        migrations.RemoveField(
            model_name='planificacionope',
            name='vregistro',
        ),
        migrations.RemoveField(
            model_name='puntoservicio',
            name='vfechaFin',
        ),
        migrations.RemoveField(
            model_name='puntoservicio',
            name='vfechaInicio',
        ),
        migrations.RemoveField(
            model_name='puntoservicio',
            name='vregistro',
        ),
        migrations.RemoveField(
            model_name='relevamientocab',
            name='vfechaFin',
        ),
        migrations.RemoveField(
            model_name='relevamientocab',
            name='vfechaInicio',
        ),
        migrations.RemoveField(
            model_name='relevamientocab',
            name='vregistro',
        ),
        migrations.RemoveField(
            model_name='relevamientocupohoras',
            name='vfechaFin',
        ),
        migrations.RemoveField(
            model_name='relevamientocupohoras',
            name='vfechaInicio',
        ),
        migrations.RemoveField(
            model_name='relevamientocupohoras',
            name='vregistro',
        ),
        migrations.RemoveField(
            model_name='relevamientodet',
            name='vfechaFin',
        ),
        migrations.RemoveField(
            model_name='relevamientodet',
            name='vfechaInicio',
        ),
        migrations.RemoveField(
            model_name='relevamientodet',
            name='vregistro',
        ),
        migrations.RemoveField(
            model_name='relevamientoesp',
            name='vfechaFin',
        ),
        migrations.RemoveField(
            model_name='relevamientoesp',
            name='vfechaInicio',
        ),
        migrations.RemoveField(
            model_name='relevamientoesp',
            name='vregistro',
        ),
        migrations.RemoveField(
            model_name='relevamientomensualeros',
            name='vfechaFin',
        ),
        migrations.RemoveField(
            model_name='relevamientomensualeros',
            name='vfechaInicio',
        ),
        migrations.RemoveField(
            model_name='relevamientomensualeros',
            name='vregistro',
        ),    
        migrations.AddField(
            model_name='histasigjefefiscal',
            name='vactual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Operarios.AsigJefeFiscal'),
        ),
    ]
