# Generated by Django 2.1.2 on 2019-07-24 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0088_auto_20190724_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistAsignacionDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunEnt', models.TimeField(blank=True, null=True, verbose_name='Lunes entradas')),
                ('lunSal', models.TimeField(blank=True, null=True, verbose_name='Lunes salida')),
                ('marEnt', models.TimeField(blank=True, null=True, verbose_name='Martes entrada')),
                ('marSal', models.TimeField(blank=True, null=True, verbose_name='Martes salida')),
                ('mieEnt', models.TimeField(blank=True, null=True, verbose_name='Miercoles entrada')),
                ('mieSal', models.TimeField(blank=True, null=True, verbose_name='Miercoles salida')),
                ('jueEnt', models.TimeField(blank=True, null=True, verbose_name='Jueves entrada')),
                ('jueSal', models.TimeField(blank=True, null=True, verbose_name='Jueves salida')),
                ('vieEnt', models.TimeField(blank=True, null=True, verbose_name='Viernes entrada')),
                ('vieSal', models.TimeField(blank=True, null=True, verbose_name='Viernes salida')),
                ('sabEnt', models.TimeField(blank=True, null=True, verbose_name='Sabado entrada')),
                ('sabSal', models.TimeField(blank=True, null=True, verbose_name='Sabado salida')),
                ('domEnt', models.TimeField(blank=True, null=True, verbose_name='Domingo entrada')),
                ('domSal', models.TimeField(blank=True, null=True, verbose_name='Domingo salida')),
                ('fechaInicio', models.DateField(null=True, verbose_name='Fecha Inicio Operario')),
                ('fechaFin', models.DateField(blank=True, null=True, verbose_name='Fecha Fin Operario')),
                ('totalHoras', models.CharField(max_length=8, null=True, verbose_name='Total Asignado')),
                ('supervisor', models.BooleanField(default=False, verbose_name='Supervisor')),
                ('vfechaInicio', models.DateTimeField(null=True, verbose_name='Fecha Inicio Reg')),
                ('vfechaFin', models.DateTimeField(null=True, verbose_name='Fecha Fin Reg')),
                ('vregistro', models.IntegerField(blank=True, null=True, verbose_name='Valor de Salario')),
                ('asignacionCab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Operarios.AsignacionCab')),
                ('operario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Operarios.Operario')),
                ('perfil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Operarios.Especializacion')),
                ('vactual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operarios.AsignacionDet')),
            ],
        )
    ]
