# Generated by Django 2.1.2 on 2019-07-24 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0089_auto_20190724_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistPlanificacionCab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Planificación')),
                ('cantidad', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de Operarios')),
                ('cantHoras', models.CharField(blank=True, max_length=8, null=True, verbose_name='Cantidad de Horas Normales')),
                ('cantHorasNoc', models.CharField(blank=True, max_length=8, null=True, verbose_name='Cantidad de Horas Nocturnas')),
                ('cantHorasEsp', models.CharField(blank=True, max_length=8, null=True, verbose_name='Cantidad de Horas Especiales')),
                ('rePlanificar', models.BooleanField(default=False, verbose_name='Re planificar')),
                ('vfechaInicio', models.DateTimeField(null=True, verbose_name='Fecha Inicio Reg')),
                ('vfechaFin', models.DateTimeField(null=True, verbose_name='Fecha Fin Reg')),
                ('vregistro', models.IntegerField(blank=True, null=True, verbose_name='Valor de Salario')),
                ('puntoServicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Operarios.PuntoServicio')),
                ('vactual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operarios.PlanificacionCab')),
            ],
        )
    ]
