# Generated by Django 2.1.2 on 2019-07-24 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0090_auto_20190724_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistPlanificacionOpe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, null=True, verbose_name='Cantidad')),
                ('lun', models.BooleanField(default=False, verbose_name='Lunes')),
                ('mar', models.BooleanField(default=False, verbose_name='Martes')),
                ('mie', models.BooleanField(default=False, verbose_name='Miercoles')),
                ('jue', models.BooleanField(default=False, verbose_name='Jueves')),
                ('vie', models.BooleanField(default=False, verbose_name='Viernes')),
                ('sab', models.BooleanField(default=False, verbose_name='Sabado')),
                ('dom', models.BooleanField(default=False, verbose_name='Domingo')),
                ('fer', models.BooleanField(default=False, verbose_name='Feriado')),
                ('ent', models.TimeField(blank=True, null=True, verbose_name='Hora Inicio')),
                ('sal', models.TimeField(blank=True, null=True, verbose_name='Hora Fin')),
                ('corte', models.CharField(blank=True, max_length=8, null=True, verbose_name='Corte')),
                ('total', models.CharField(blank=True, max_length=8, null=True, verbose_name='Total')),
                ('vfechaInicio', models.DateTimeField(null=True, verbose_name='Fecha Inicio Reg')),
                ('vfechaFin', models.DateTimeField(null=True, verbose_name='Fecha Fin Reg')),
                ('vregistro', models.IntegerField(blank=True, null=True, verbose_name='Valor de Salario')),
                ('especialista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Operarios.Especializacion')),
                ('planificacionCab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Operarios.PlanificacionCab')),
                ('vactual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operarios.PlanificacionOpe')),
            ],
        )
    ]
