# Generated by Django 2.1.2 on 2019-07-24 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0092_auto_20190724_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistPuntoServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodPuntoServicio', models.CharField(max_length=50, verbose_name='Punto de Servicio')),
                ('NombrePServicio', models.CharField(max_length=100, verbose_name='Nombre de Punto de Servicio')),
                ('DireccionContrato', models.CharField(max_length=150, verbose_name='Direccion del Punto de Servicio')),
                ('Barrios', models.CharField(max_length=70, verbose_name='Barrio')),
                ('Contacto', models.CharField(max_length=100, verbose_name='Nombre del Contacto')),
                ('MailContacto', models.CharField(blank=True, max_length=70, verbose_name='E-Mail Contacto')),
                ('TelefonoContacto', models.CharField(max_length=100, verbose_name='Telefono del Contacto')),
                ('Coordenadas', models.CharField(max_length=100, verbose_name='Coordenadas')),
                ('NumeroMarcador', models.CharField(blank=True, max_length=15, null=True, verbose_name='Numero Marcador')),
                ('vfechaInicio', models.DateTimeField(null=True, verbose_name='Fecha Inicio Reg')),
                ('vfechaFin', models.DateTimeField(null=True, verbose_name='Fecha Fin Reg')),
                ('vregistro', models.IntegerField(blank=True, null=True, verbose_name='Valor de Salario')),
                ('Ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operarios.Ciudad')),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operarios.Cliente')),
                ('vactual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operarios.PuntoServicio')),
            ],
        ),
    ]
