# Generated by Django 2.1.2 on 2019-07-24 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Operarios', '0093_auto_20190724_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistRelevamientoCab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Relevamiento')),
                ('cantidad', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de Operarios')),
                ('cantAprendices', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de Aprendices')),
                ('cantidadHrTotal', models.CharField(blank=True, max_length=8, null=True, verbose_name='Cantidad de Horas total por Semana')),
                ('cantidadHrEsp', models.CharField(blank=True, max_length=8, null=True, verbose_name='Cantidad de Horas Especiales por Semana')),
                ('fechaInicio', models.DateField(null=True, verbose_name='Fecha Inicio Cobertura')),
                ('fechaFin', models.DateField(blank=True, null=True, verbose_name='Fecha Fin Cobertura')),
                ('estado', models.CharField(default='Aprobado', max_length=30, verbose_name='Estado del relevamiento')),
                ('comentario', models.CharField(blank=True, max_length=550, null=True, verbose_name='Comentarios del servicio aprobado')),
                ('vfechaInicio', models.DateTimeField(null=True, verbose_name='Fecha Inicio Reg')),
                ('vfechaFin', models.DateTimeField(null=True, verbose_name='Fecha Fin Reg')),
                ('vregistro', models.IntegerField(blank=True, null=True, verbose_name='Valor de Salario')),
                ('puntoServicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Operarios.PuntoServicio')),
                ('tipoSalario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Operarios.TipoSalario')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vactual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operarios.RelevamientoCab')),
            ],
        ),
       
    ]
