# Generated by Django 2.1.2 on 2019-07-24 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0096_auto_20190724_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistRelevamientoCupoHoras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantCHoras', models.CharField(blank=True, db_column='cantHoras', max_length=8, null=True, verbose_name='Cantidad de Horas')),
                ('frecuencia', models.CharField(choices=[('SEM', 'Semanal'), ('DOM', 'Domingo'), ('FER', 'Feriado')], default='SEM', max_length=3, verbose_name='Frecuencia')),
                ('vfechaInicio', models.DateTimeField(null=True, verbose_name='Fecha Inicio Reg')),
                ('vfechaFin', models.DateTimeField(null=True, verbose_name='Fecha Fin Reg')),
                ('vregistro', models.IntegerField(blank=True, null=True, verbose_name='Valor de Salario')),
                ('relevamientoCab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Operarios.RelevamientoCab')),
                ('tipoHora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Operarios.TipoHorario')),
                ('vactual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operarios.RelevamientoCupoHoras')),
            ],
        ),
        
    ]
