# Generated by Django 2.1.2 on 2019-07-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0098_auto_20190724_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='histasigfiscalpuntoservicio',
            name='puntoServicio',
        ),
        migrations.RemoveField(
            model_name='histasigfiscalpuntoservicio',
            name='userFiscal',
        ),
        migrations.RemoveField(
            model_name='histasigjefefiscal',
            name='userFiscal',
        ),
        migrations.RemoveField(
            model_name='histasigjefefiscal',
            name='userJefe',
        ),
        
    ]
