# Generated by Django 2.1.2 on 2019-07-25 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0100_auto_20190725_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histasignacioncab',
            name='vactual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Operarios.AsignacionCab'),
        ),
        migrations.AlterField(
            model_name='histasignaciondet',
            name='vactual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Operarios.AsignacionDet'),
        ),
        migrations.AlterField(
            model_name='histplanificacioncab',
            name='vactual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Operarios.PlanificacionCab'),
        ),
        migrations.AlterField(
            model_name='histplanificacionesp',
            name='vactual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Operarios.PlanificacionEsp'),
        ),
        migrations.AlterField(
            model_name='histplanificacionope',
            name='vactual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Operarios.PlanificacionOpe'),
        ),
        migrations.AlterField(
            model_name='histpuntoservicio',
            name='vactual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Operarios.PuntoServicio'),
        ),
        migrations.AlterField(
            model_name='histrelevamientocab',
            name='vactual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Operarios.RelevamientoCab'),
        ),
        migrations.AlterField(
            model_name='histrelevamientocupohoras',
            name='vactual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Operarios.RelevamientoCupoHoras'),
        ),
        migrations.AlterField(
            model_name='histrelevamientodet',
            name='vactual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Operarios.RelevamientoDet'),
        ),
        migrations.AlterField(
            model_name='histrelevamientoesp',
            name='vactual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Operarios.RelevamientoEsp'),
        ),
        migrations.AlterField(
            model_name='histrelevamientomensualeros',
            name='vactual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Operarios.RelevamientoMensualeros'),
        ),
    ]
