# Generated by Django 2.1.2 on 2019-08-01 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0103_auto_20190731_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='CupoUtilizado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anho', models.IntegerField(blank=True, null=True, verbose_name='Anho del cupo')),
                ('mes', models.CharField(max_length=2, verbose_name='Mes del cupo del anho')),
                ('cupoUtilizado', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de horas totales usadas por hora procesada')),
                ('horasProcesadas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Operarios.HorasProcesadas')),
                ('puntoServicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Operarios.PuntoServicio')),
            ],
        ),
        
    ]
