# Generated by Django 2.1.2 on 2019-08-06 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0104_auto_20190801_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionDetTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunEnt', models.TimeField(blank=True, null=True, verbose_name='Lunes entradas')),
                ('lunSal', models.TimeField(blank=True, null=True, verbose_name='Lunes salida')),
                ('marEnt', models.TimeField(blank=True, null=True, verbose_name='Martes entrada')),
                ('marSal', models.TimeField(blank=True, null=True, verbose_name='Martes salida')),
                ('mieEnt', models.TimeField(blank=True, null=True, verbose_name='Miercoles entrada')),
                ('mieSal', models.TimeField(blank=True, null=True, verbose_name='Miercoles salida')),
                ('jueEnt', models.TimeField(blank=True, null=True, verbose_name='Jueves entrada')),
                ('jueSal', models.TimeField(blank=True, null=True, verbose_name='Jueves salida')),
                ('vieEnt', models.TimeField(blank=True, null=True, verbose_name='Viernes entrada')),
                ('vieSal', models.TimeField(blank=True, null=True, verbose_name='Viernes salida')),
                ('sabEnt', models.TimeField(blank=True, null=True, verbose_name='Sabado entrada')),
                ('sabSal', models.TimeField(blank=True, null=True, verbose_name='Sabado salida')),
                ('domEnt', models.TimeField(blank=True, null=True, verbose_name='Domingo entrada')),
                ('domSal', models.TimeField(blank=True, null=True, verbose_name='Domingo salida')),
                ('fechaInicio', models.DateField(null=True, verbose_name='Fecha Inicio Operario')),
                ('fechaFin', models.DateField(blank=True, null=True, verbose_name='Fecha Fin Operario')),
                ('totalHoras', models.CharField(max_length=8, null=True, verbose_name='Total Asignado')),
                ('supervisor', models.BooleanField(default=False, verbose_name='Supervisor')),
                ('eliminado', models.BooleanField(default=False, verbose_name='Registro temporal eliminado')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creacion del registro')),
                ('asignacionCab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Operarios.AsignacionCab')),
                ('operario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Operarios.Operario')),
                ('perfil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Operarios.Especializacion')),
            ],
            options={
                'verbose_name': 'Asignacion Detalle Temp',
                'verbose_name_plural': 'Asignacion Detalles Temp',
            },
        ),
        migrations.AddField(
            model_name='asignaciondet',
            name='eliminado',
            field=models.BooleanField(default=False, verbose_name='Registro eliminado'),
        ),
        ]
