# Generated by Django 2.1.2 on 2019-08-13 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0056_auto_20190530_2022'),
        ('Operarios', '0105_auto_20190806_1453'),
    ]

    operations = [
    ]
