# Generated by Django 2.1.2 on 2019-08-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operarios', '0106_merge_20190813_0929'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='alertas',
            name='Nivel',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nivel Alerta'),
        )
    ]
